BEGIN
-- CLOTHING_LOOKUP
INSERT INTO CLOTHING_LOOKUP (CLOTHING_ID, CLOTHING)
SELECT CLOTHING_ID, CLOTHING FROM seed.CLOTHING_LOOKUP;

-- COLOR_LOOKUP
INSERT INTO COLOR_LOOKUP (COLOR_ID, COLOR)
SELECT COLOR_ID, COLOR FROM seed.COLOR_LOOKUP;

-- DEPARTMENT_LOOKUP
INSERT INTO DEPARTMENT_LOOKUP (DEPARTMENT_ID, DEPARTMENT)
SELECT DEPARTMENT_ID, DEPARTMENT FROM seed.DEPARTMENT_LOOKUP;


-- PRODUCTS
INSERT INTO PRODUCTS (
    PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, PRODUCT_DETAILS, PRODUCT_IMAGE, 
    IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED, 
    COLOR_ID, DEPARTMENT_ID, CLOTHING_ID
)
SELECT PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, PRODUCT_DETAILS, PRODUCT_IMAGE, 
       IMAGE_MIME_TYPE, IMAGE_FILENAME, IMAGE_CHARSET, IMAGE_LAST_UPDATED, 
       COLOR_ID, DEPARTMENT_ID, CLOTHING_ID
FROM seed.PRODUCTS;

-- STORES
INSERT INTO STORES (
    STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE,
    LOGO, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED
)
SELECT STORE_ID, STORE_NAME, WEB_ADDRESS, PHYSICAL_ADDRESS, LATITUDE, LONGITUDE,
       LOGO, LOGO_MIME_TYPE, LOGO_FILENAME, LOGO_CHARSET, LOGO_LAST_UPDATED
FROM seed.STORES;

-- CUSTOMERS
INSERT INTO CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL_ADDRESS)
SELECT CUSTOMER_ID, FULL_NAME, EMAIL_ADDRESS FROM seed.CUSTOMERS;

-- DEPARTMENTS
INSERT INTO DEPARTMENTS (ID, NAME, LOCATION, COUNTRY)
SELECT ID, NAME, LOCATION, COUNTRY FROM seed.DEPARTMENTS;

-- EMPLOYEES
INSERT INTO EMPLOYEES (
    DEPARTMENT_ID, NAME, EMAIL, COST_CENTER, DATE_HIRED, JOB
)
SELECT DEPARTMENT_ID, NAME, EMAIL, COST_CENTER, DATE_HIRED, JOB
FROM seed.EMPLOYEES;

-- ORDERS
INSERT INTO ORDERS (
    ORDER_ID, ORDER_DATETIME, CUSTOMER_ID, ORDER_STATUS, STORE_ID,
    STAR_RATING, FEEDBACK, EMAIL_FLAGGED
)
SELECT ORDER_ID, ORDER_DATETIME, CUSTOMER_ID, ORDER_STATUS, STORE_ID,
       STAR_RATING, FEEDBACK, EMAIL_FLAGGED
FROM seed.ORDERS;

-- ORDER_ITEMS
INSERT INTO ORDER_ITEMS (
    ORDER_ID, LINE_ITEM_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY
)
SELECT ORDER_ID, LINE_ITEM_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY
FROM seed.ORDER_ITEMS;

-- PROJECTS
INSERT INTO PROJECTS (
    ID, PROJECT, TASK_NAME, START_DATE, END_DATE, ASSIGNED_TO, COST, BUDGET, STATUS
)
SELECT ID, PROJECT, TASK_NAME, START_DATE, END_DATE, ASSIGNED_TO, COST, BUDGET, STATUS
FROM seed.PROJECTS;

COMMIT;
END;
